### ISSUE TITLE
part 2 contains many empty rows

### ISSUE THREAD

**Issue by eyaler** [mattbierner/urban-dictionary-entry-collector#1]
part 2 contains many empty rows

**Comment by mattbierner** [comment]
Looks like fusion tables didn't like the CSV for that set and created these empty rows. This should be fixed now: https://www.google.com/fusiontables/DataSource?docid=1U3EBCIDshan_-7mF556LVDX8L_vPKJJco882RLPw

Now each set has the proper ~500,000 entries or so, but if you are processing the data you may still run into a few empty rows or rows that don't have the proper data. After quick scan most of it looks good now though.
